"""Make users.channel_id nullable

Revision ID: a60c1ea66e69
Revises: a8a5696d1098
Create Date: 2025-12-01 19:50:15.728655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60c1ea66e69'
down_revision: Union[str, Sequence[str], None] = 'a8a5696d1098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'channel_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'channel_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
