from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid # <-- Ensure this import is at the top of your migration file

# revision identifiers, used by Alembic.
revision: str = 'a8a5696d1098'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # ----------------------------------------------------------------------
    # *** CRITICAL: REPLACE THIS PLACEHOLDER UUID ***
    # This must be the UUID of a valid, existing channel in your 'channels' table.
    DEFAULT_CHANNEL_UUID = "e0c07381-b694-4751-987d-51ea742bd5b1"
    # ----------------------------------------------------------------------
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # All op.alter_column commands remain the same
    op.alter_column('calendar_events', 'workspace_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('calendar_events', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.drop_constraint(op.f('channel_members_channel_id_user_id_key'), 'channel_members', type_='unique')
    op.alter_column('channels', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('ideas', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('ideas', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('messages', 'channel_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('messages', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('messages', 'file_type',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('messages', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('reactions', 'message_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('reactions', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('reactions', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    
    # --- FIXED 3-STEP LOGIC FOR users.channel_id ---
    
    # 1. Add the column with nullable=True temporarily (MUST be sa.UUID() type)
    op.add_column('users', sa.Column('channel_id', sa.UUID(), nullable=True)) 

    # 2. Populate existing rows with a valid default UUID
    op.execute(
        f"UPDATE users SET channel_id = '{DEFAULT_CHANNEL_UUID}' WHERE channel_id IS NULL"
    )

    # 3. Alter the column to enforce NOT NULL 
    op.alter_column('users', 'channel_id',
                    existing_type=sa.UUID(),
                    nullable=False) 
    
    # 4. Add the Foreign Key constraint (using an explicit name is best practice)
    op.create_foreign_key(
        'fk_users_channel_id_channels_id', 'users', 'channels', ['channel_id'], ['id']
    )
    
    # --- Remaining original commands ---
    op.alter_column('users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    # The original create_foreign_key(None, 'users', 'channels', ['channel_id'], ['id']) is removed as it's replaced above.
    op.alter_column('workspaces', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    # Ensure the named constraint is dropped
    op.drop_constraint('fk_users_channel_id_channels_id', 'users', type_='foreignkey') 
    op.alter_column('users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_column('users', 'channel_id')
    op.alter_column('reactions', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('reactions', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('reactions', 'message_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('messages', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('messages', 'file_type',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('messages', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('messages', 'channel_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('ideas', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('ideas', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('channels', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.create_unique_constraint(op.f('channel_members_channel_id_user_id_key'), 'channel_members', ['channel_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('calendar_events', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('calendar_events', 'workspace_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###